### ISSUE TITLE
Why only capital? 

### ISSUE THREAD

**Issue by mjmajadly** [WebAhead7/Weather-App#11]
You have only capital country search available. 
That said, when you enter other cities, it does change all the data within the app (except for the capital name and flag image).

You should have some sort of function that doesn't change the data (temperatures) when you enter city names that are not the capital

**Comment by rakad-kh** [comment]
No, the weather information is available for all the cities abroad.
try it your self :)
(anyway, we still working on finding api that return for given city the related capital)
