### ISSUE TITLE
overall

### ISSUE THREAD

**Issue by mjmajadly** [WebAhead7/Weather-App#14]
overall I like the background, but the API needs more work. Looks like its a limited API. Our team spent all day Tuesday looking for APIs that give us the functionality that is needed.

The code is too complex (min_temp, max_temp), in the right API, that information is giving.

**Comment by rakad-kh** [comment]
Thank you for your reply, but actually Mukha spent a lot of time searching for an api that return the capital name for given city, he is still looking for one, and in case we found we will update immediately.
Anyway you can get weather information of any city you want in our website.
thank you.
