### ISSUE TITLE
Not a readable line of code

### ISSUE THREAD

**Issue by shiryz** [WebAhead7/Weather-App#7]
https://github.com/WebAhead7/Weather-App/blob/main/weather-app.js#L41

What is going on here?
There are too many functions being executed, I don't see the point of using both map and reduce, you can also use JS syntax for min and max

**Comment by rakad-kh** [comment]
it is more simple and naive to use min/max, but think you prefer reduce and map upon math.min/max.
Although, I've changed it and returned to the easy syntaxes.
thank you
