### ISSUE TITLE
Repetitive code

### ISSUE THREAD

**Issue by shiryz** [WebAhead7/Weather-App#8]
The same confusing line of code which no developer would try to read has been written twice :exploding_head: 
https://github.com/WebAhead7/Weather-App/blob/main/weather-app.js#L41-L42
This code is not clean, please make something more abstract and readable.

**Comment by shiryz** [comment]
It's happening again https://github.com/WebAhead7/Weather-App/blob/main/weather-app.js#L53-L54 and it's even more of that code

**Comment by shiryz** [comment]
And again and again and one more time 
https://github.com/WebAhead7/Weather-App/blob/main/weather-app.js#L60-L69

**Comment by rakad-kh** [comment]
fixed
