### ISSUE TITLE
Your JS code is not well structured and is what we call spaghetti code 

### ISSUE THREAD

**Issue by shiryz** [WebAhead7/Weather-App#9]
> Spaghetti code is a pejorative phrase for unstructured and difficult-to-maintain source code. Spaghetti code can be caused by several factors, such as volatile project requirements, lack of programming style rules, and insufficient ability or experience.

If you write your code in a manner where you just want to finish and have it do what's it's supposed to do then it will look the way it does in your JS file. It looks messy, unreadable, too long, and repetitive! this type of code is unmaintainable and doesn't make any sense unless someone wants to try really hard to understand it. 

You need to go over it again and try to use either easier ways to write or abstract some of the functions that you've written.

**Comment by rakad-kh** [comment]
fixed
